<?php

/**
 * @file
 * Contains webform_client_creator.module.
 */

/**
 * Implements hook_theme().
 */
function webform_client_creator_theme($existing, $type, $theme, $path) {
  return array(
    'confirmation_mail' => array(
      'variables' => array(
        'newUserName' => null,
        'password' => null
      )
    )
  );
}

/**
 * Implements hook_mail().
 */
function webform_client_creator_mail($key, &$message, $params) {
  switch ($key) {
    case 'create_user':
      $message['headers']['Content-Type'] = 'text/html';
      $message['format'] = 'text/html';
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}
