<?php

function webform_client_creator_mail($key, &$message, $params) {
  switch ($key) {
    case 'create_user':
    case 'general_mail':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = Html::escape($params['body']);
      break;
  }
}

function webform_client_creator_node_insert(Drupal\Core\Entity\EntityInterface $entity)
{
  drupal_set_message($entity->getEntityType());
  $mailManager = \Drupal::service('plugin.manager.mail');
  $module = 'webform_client_creator';
  $key = 'create_user';
  $to = $entity->getEmail();
  $params['message'] = "Welcome to our site! \r\nYour username is " . $entity->getUsername() . " " . "\r\nIf you would like to reset your password, you can at the following link: \r\n" . user_pass_reset_url($entity);
  $langcode = $entity->getPreferredLangcode();


  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, TRUE);
  if ($result['result'] !== true) {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }
  else {
    drupal_set_message(t('Your message has been sent.'));
  }
  if($entity->getEntityType() == 'client') {
  }
}
